# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/setup-go@v1
      with:
        go-version: '1.13.5'
    - uses: jpkrohling/setup-minikube@v1-release
      with:
        minikube-version: v1.5.2
    # 1.3.1 --          kubernetes 1.15.2
    # 1.4.0 -- failed
    # 1.5.0 -- worked
    # 1.5.1 -- worked
    # 1.5.2 -- worked
    # 1.6.0 -- worked  kubeernetes 1.17.0
    # 1.6.1
    # 1.6.2 -- worked  kubernetes  1.17.0
    # 1.7.0
    # 1.7.1
    # 1.7.2 -- failed
    # 1.7.3
    # 1.8.0
    # 1.8.1
    # 1.8.2 -- failed
    # 1.9.0
    # 1.9.1
    # 1.9.2


      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: echo Hello, world!

    - name: Test
      run: go test -v .

    - name: "setup docker"
      run: ./.ci/setup-docker.sh

    - name: "start minikube"
      run: ./.ci/start-minikube.sh

    - name: "Versions"
      run: ./.ci/check-versions.sh

